### PR TITLE
Fixing cache management

### LINKED ISSUE #155: about cache management
Hello !
Thanks for sharing this great library !

i've created a sandbox here : https://github.com/soolidtech/test-i18n-cache

it looks like with this library, we have two possibilities for managing translations cache : 
- cached
- not cached (fresh opt set to true)

The thing is that cached setting makes it impossible to get new translation versions except if one clean his browser's cache.
Repro can be observed by cloning my repository `https://github.com/soolidtech/test-i18n-cache`

steps to reproduce :
`npm run start`
- change locale to french on app screen
- screen displays "Bonjour" => ok
- change content of `imports/i18n/fr/Test.i18n.yml` file with a new translation like "Bonjour Monde" and save
- refresh app screen
- change locale to french on app screen
- Content is still "Bonjour"

I don't want to use "fresh" neither since it's overkill

Could we consider using etag like Meteor team does in its docs about serving a static content ?
https://docs.meteor.com/packages/webapp.html#Serving-a-Static-Landing-Page

This way, cache would be invalidated if any translation changes

Thanks for reading

### PR DESCRIPTION
**Pull request by zendranm**
Closes #155.

### CODE REVIEW

File: source/server.ts [hunk 1]
```diff
@@ -38,9 +38,7 @@ function getJS(locale: string, namespace?: string, isBefore?: boolean) {
     ? `var w=this||window;w.__uniI18nPre=w.__uniI18nPre||{};w.__uniI18nPre['${locale}${
         namespace && typeof namespace === 'string' ? `.${namespace}` : ''
```
Comment (radekmie) [inline source/server.ts:39]: I think we could get rid of the `typeof` check here.

File: source/utils.ts [hunk 2]
```diff
@@ -38,3 +38,13 @@ export function set(object: UnknownRecord, path: string, value: unknown) {
 
   object[last] = value;
 }
+
+export function getAddCachedTranslationsJS(
```
Comment (radekmie) [inline source/utils.ts:42]: How about moving all of the code-generation helpers to one file (`getJS`, etc.)? `utils.ts` is bundled in the client's code as well but it's not needed there.

File: source/code-generators.ts [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+  return function cached(
+    locale: string,
+    localeCache: Record<string, string>,
+    namespace?: string,
+    diffWith?: string,
+  ) {
+    const { get, key } = cacheEntry(locale, namespace, diffWith);
+    if (!(key in localeCache)) {
+      localeCache[key] = get();
+    }
```
Comment (radekmie) [inline source/code-generators.ts:55]: Previously the cached objects were exposed through `i18n.getCache`, and as I checked, one of our projects relies on that (it clears it). Right now, this cache is not clearable, so it's a rather breaking change.

Is there any particular reason why you changed that?

Comment (zendranm) [reply source/code-generators.ts:55]: Previously the `getCachedFormatter` function was in the `server.ts` file and accessed the `cache` object directly to get the `localeCache` value. Since this function is now kept in a separate file it cannot access the `cache` object as previously, so instead it takes that as an argument.

But when we are [calling this function](https://github.com/vazco/meteor-universe-i18n/blob/cache-fix/source/server.ts#LL176C9-L176C80) we actually [use `cache`](https://github.com/vazco/meteor-universe-i18n/blob/cache-fix/source/server.ts#L167) exposed via the `i18n.getCache`. Which change breaks the cache-clearing logic?

Comment (radekmie) [reply source/code-generators.ts:55]: > Previously the `getCachedFormatter` function was in the `server.ts` file and accessed the `cache` object directly to get the `localeCache` value. Since this function is now kept in a separate file it cannot access the `cache` object as previously, so instead it takes that as an argument.

It can be accessed using `i18n.getCache()` now.

> But when we are [calling this function](https://github.com/vazco/meteor-universe-i18n/blob/cache-fix/source/server.ts#LL176C9-L176C80) we actually [use `cache`](https://github.com/vazco/meteor-universe-i18n/blob/cache-fix/source/server.ts#L167) exposed via the `i18n.getCache`. Which change breaks the cache-clearing logic?

The thing is, it's spread now, so writing to it won't change the `cache` object at all.

**Review by radekmie — APPROVED** [review]

File: source/code-generators.ts (hunk 3 above)
Comment (zendranm) [reply source/code-generators.ts]: Right, that makes sense - I wanted to black-box the `getCachedFormatter` function as much as possible since we already are accessing the cache before calling it, but it doesn't make sense to do that since getting cache from `i18n.getCache` is way simpler.
